<a href="https://colab.research.google.com/github/subashnamaskey/2462341_SubashnaMaskey/blob/main/2462341_SubashnaMaskey.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

WORKSHOP 1

1. Initialize an empty array with size 2X2.

Task 1

In [ ]:
import numpy as np
arr1 = np.zeros((2, 2))
print(arr1)

[[0. 0.]
 [0. 0.]]


2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np
arr2 = np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
arr3 = np.full((3, 3), 7)
print(arr3)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
arr4 = np.zeros_like(arr2)
print(arr4)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
arr5 = np.ones_like(arr2)
print(arr5)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print(arr6)

[1 2 3 4]


Task 2

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

arr1 = np.arange(10, 50)
print(arr1)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}

In [ ]:
arr2 = np.arange(0,9).reshape(3, 3)
print(arr2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
arr3 = np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
arr4 = np.random.random(30)
mean_value = arr4.mean()
print(arr4)
print("Mean:", mean_value)

[0.05661281 0.12208849 0.49123499 0.87499627 0.76582182 0.42903866
 0.28970117 0.68999668 0.61641478 0.48943949 0.27688125 0.31383512
 0.98500792 0.31455007 0.68665207 0.0997391  0.64615087 0.8030451
 0.04723517 0.21852485 0.79540208 0.67492215 0.32413324 0.69741654
 0.98027772 0.03111516 0.75094431 0.03997657 0.64780774 0.97476014]
Mean: 0.5044574108076094


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
arr5 = np.random.random((10, 10))
min_val = arr5.min()
max_val = arr5.max()
print("Min:", min_val)
print("Max:", max_val)

Min: 0.017985624316499416
Max: 0.9922868348237072


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
arr6 = np.zeros(10)
arr6[4] = 1
print(arr6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print(arr8)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
arr9 = np.zeros((8, 8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print(arr9)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Task 3
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:

1. Add the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])
add_xy = x + y
print(add_xy)

[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
sub_xy = x - y
print(sub_xy)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
mul_x = x * 3
print(mul_x)


[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [ ]:
square_x = x ** 2
print(square_x)

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
dot_vw = np.dot(v, w)
print(dot_vw)

219


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.


In [ ]:
concatenate_xy_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concatenate_xy_row)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
try:
    concat_x_v = np.concatenate((x, v), axis=0)
except Exception as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Explanation:
You get an error because x is a 2D array of shape (2,2) and v is a 1D array of shape (2,). NumPy cannot concatenate arrays of different dimensions along axis 0 without reshaping.

In [ ]:
#If the solution needs to work
# make it 2D
v_reshaped = v.reshape(1,2)
concat_x_v_fixed = np.concatenate((x, v_reshaped), axis=0)
print(concat_x_v_fixed)


[[ 1  2]
 [ 3  5]
 [ 9 10]]


Henceforth, this makes it totally plausible for correct concatenation

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


1. Prove
𝐴⋅𝐴−1 = 𝐼

In [ ]:
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)

print("A · A_inv =\n", identity)

A · A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove 𝐴𝐵≠𝐵𝐴

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal? ", np.array_equal(AB, BA))


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Are AB and BA equal?  False


3. Prove (𝐴𝐵)𝑇=𝐵𝑇𝐴𝑇

In [ ]:
AB_T = (np.dot(A, B)).T
B_TA_T = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("B^T · A^T =\n", B_TA_T)
print("Are they equal?", np.array_equal(AB_T, B_TA_T))


(AB)^T =
 [[23 51]
 [13 29]]
B^T · A^T =
 [[23 51]
 [13 29]]
Are they equal? True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

In [ ]:
# Coefficient matrix A
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

# Constant matrix B
B_eq = np.array([-1, -3, 9])


Using inverse to solve the equations

In [ ]:
X = np.dot(np.linalg.inv(A_eq), B_eq)
print("Solution [x, y, z] =", X)


Solution [x, y, z] = [ 2.  1. -2.]


Now aolving using np.linalg.inv function

In [ ]:
A_inv = np.linalg.inv(A_eq)
X = np.dot(A_inv, B_eq)
print("Solution [x, y, z] =", X)

Solution [x, y, z] = [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:

1.Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time
#here we are declaring the size of the arrays
N = 1_000_000

# Python lists
list1 = list(range(N))
list2 = list(range(N))

# NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)
start_time = time.time()

# Using list comprehension for element-wise addition
list_sum = [list1[i] + list2[i] for i in range(N)]

end_time = time.time()
print("Time taken for Python lists addition: {:.5f} seconds".format(end_time - start_time))
start_time = time.time()

# Using NumPy's vectorized addition
array_sum = arr1 + arr2

#displaying the result of the difference of the time between element wise and numpy additions
end_time = time.time()
print("Time taken for NumPy arrays addition: {:.5f} seconds".format(end_time - start_time))


Time taken for Python lists addition: 0.10602 seconds
Time taken for NumPy arrays addition: 0.00487 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea- sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
#Now we will try with multiplications
import numpy as np
import time

#declaring the size fo arrays
N = 1_000_000

# Python lists
list1 = list(range(1, N+1))
list2 = list(range(1, N+1))

# NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)
start_time = time.time()

# Using list comprehension for multiplication
list_mul = [list1[i] * list2[i] for i in range(N)]

end_time = time.time()
print("Time taken for Python lists multiplication: {:.5f} seconds".format(end_time - start_time))
start_time = time.time()

# Using NumPy vectorized multiplication
array_mul = arr1 * arr2

#displaying the result of the difference of the time between element wise and numpy multiplications
end_time = time.time()
print("Time taken for NumPy arrays multiplication: {:.5f} seconds".format(end_time - start_time))


Time taken for Python lists multiplication: 0.24439 seconds
Time taken for NumPy arrays multiplication: 0.00347 seconds


3.Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time
#declaring arryas of huge size
N = 1_000_000

# Python lists
list1 = list(range(1, N+50))
list2 = list(range(1, N+50))

# NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)
start_time = time.time()

# Compute dot product manually
dot_list = sum(list1[i] * list2[i] for i in range(N))

end_time = time.time()
print("Time taken for Python lists dot product: {:.5f} seconds".format(end_time - start_time))
start_time = time.time()

# Using NumPy's dot function
dot_array = np.dot(arr1, arr2)

#displaying the result of the difference of the time between the python list dot product and numpy dot product
end_time = time.time()
print("Time taken for NumPy arrays dot product: {:.5f} seconds".format(end_time - start_time))


Time taken for Python lists dot product: 0.25739 seconds
Time taken for NumPy arrays dot product: 0.00248 seconds


4.Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time
import random
N = 1000

# Generate 1000x1000 matrices with random integers 0-10
matrix1 = [[random.randint(0, 10) for _ in range(N)] for _ in range(N)]
matrix2 = [[random.randint(0, 10) for _ in range(N)] for _ in range(N)]
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)
start_time = time.time()

# Initialize result matrix with zeros
result_list = [[0 for _ in range(N)] for _ in range(N)]

# Perform multiplication
for i in range(N):
    for j in range(N):
        for k in range(N):
            result_list[i][j] += matrix1[i][k] * matrix2[k][j]

end_time = time.time()
print("Time taken for Python lists matrix multiplication: {:.5f} seconds".format(end_time - start_time))
start_time = time.time()

result_np = np.dot(np_matrix1, np_matrix2)  # or np_matrix1 @ np_matrix2

end_time = time.time()
print("Time taken for NumPy arrays matrix multiplication: {:.5f} seconds".format(end_time - start_time))


Time taken for Python lists matrix multiplication: 272.85464 seconds
Time taken for NumPy arrays matrix multiplication: 2.49089 seconds


Therefore, this makes to a conclusion on how NumPy arrays are way more faster than simple Python arrays computations.